### ISSUE TITLE
I got a issue on line 270

### ISSUE THREAD

**Issue by LukeWANGNJ** [Sven-Bo/Integrate-ChatGPT-in-Excel-using-VBA#2]
Error -2146697208: The download of the specified resource
has failed.
Line: 270

```
          ' Open and send the HTTP request
230       With httpRequest
240           .Open "POST", API_ENDPOINT, False
250           .SetRequestHeader "Content-Type", "application/json"
260           .SetRequestHeader "Authorization", "Bearer " & API_KEY
270           .send (requestBody)
280       End With
```

**Comment by LukeWANGNJ** [comment]
Hi,

I've tried to replace line 210
`Set httpRequest = CreateObject("MSXML2.XMLHTTP")`
to
`Set httpRequest = CreateObject("WinHttp.WinHttpRequest.5.1")`


and now I got another error
`Error -2147012866: The connection with the server was
terminated abnormally
Line: 270`

**Comment by Sven-Bo** [comment]
See Issue #1
