### ISSUE TITLE
unwanted txt in row 1-result sheet

### ISSUE THREAD

**Issue by baba-lds** [Sven-Bo/Integrate-ChatGPT-in-Excel-using-VBA#7]
1. Unwanted txt appears in row 1 of results sheet e
ex: """: ""cmpl-7PXG9Dd2yPXVFWvCmqVkhevFy0LV1"",
  ""object"": ""text_completion"",
  ""created"": 1686320405,
  ""model"": ""text-davinci-003"",
  ""choices"": [
    {
      ""text"": """
2. with the results there is ', extra. Need help to remove this .

**Comment by Sven-Bo** [comment]
Hey @baba-lds ,
Thanks for your input. Right now, I'm pretty swamped with other stuff, so I won't be making changes or updates to the code. Feel free to fork the repo and make changes as you see fit though.
