### ISSUE TITLE
how to download email attached to an outlook email 

### ISSUE THREAD

**Issue by gpcr** [Sven-Bo/Integrate-ChatGPT-in-Excel-using-VBA#8]
The attached email to the primary email has an attachment file. How to download that attachment file not the attached email

**Comment by Sven-Bo** [comment]
Thanks for the issue. It seems unrelated to this repo's scope. If it's relevant to this project, please provide more details. Otherwise, I'd recommend finding a more appropriate repo for your concern. Closing this for now, but happy to revisit if needed.
